### ISSUE TITLE
Evaluation using newer open-source models

### ISSUE THREAD

**Issue by chubzchubz97** [sonqt/agent-unanswerable#1]
Hi,

Have you evaluated the performance of models like FLAN-T5 on your dataset?

**Comment by sonqt** [comment]
Hi, 
We have not evaluated FLAN-T5 on our dataset. We recently published our dataset on [huggingface hub](https://huggingface.co/datasets/sonquoctran/SQuAD_AGent). You can evaluate other models on it.
